version: '3.8'

services:
  app:
    image: tejaroyal/backend-app  # Ensure it matches pipeline
    ports:
      - "80:80"
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    networks:
      - mynetwork
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      db:
        condition: service_healthy  # Ensures DB is ready before starting app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

networks:
  mynetwork:
    driver: overlay

volumes:
  pgdata:
