version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    networks:
      - my_network
    ports:
      - "80:80"
    volumes:
      - nginx_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom config

  test_container:
    image: alpine
    container_name: test_container
    networks:
      - my_network
    depends_on:
      - nginx
    command: sh -c "apk add --no-cache curl && while true; do curl -s http://nginx; sleep 5; done"

volumes:
  nginx_data:

networks:
  my_network:
    driver: overlay  # For Docker Swarm
