version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    networks:
      - mynetwork
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  mynetwork:
    driver: overlay

volumes:
  pgdata:
